services:
  - type: web
    name: aduavir-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app_v2_1_7.py --server.port=$PORT --server.address=0.0.0.0
    plan: free